很惭愧，就做了一点微小的工作
SO-TS/but pull request #2
Opened 2024-07-06 09:18 UTC by MCSeekeri

- 加入了文件修改检测，仅在最后修改时间变动时进行备份
- 支持 zstd 压缩
- 将依赖库升级为最新版本
- 去除无用依赖
- 实验性支持配置文件热重载
- 实验性加入 SystemD 支持

2024-07-07 07:10 UTC, ApartTUSITU commented
等待与主要贡献者商讨。

2024-07-07 07:13 UTC, ApartTUSITU commented
提醒您，请不要对仓库README.md文件擅自作出重大改动。

2024-07-07 07:16 UTC, MCSeekeri commented
> 提醒您，请不要对仓库README.md文件擅自作出重大改动。

考虑到原本的 README.md 文件较为简陋，加入配置文件示例及使用帮助是应当的。

2024-07-07 07:18 UTC, ApartTUSITU commented
请您逐步证明自己的实力，本项目随时欢迎您的贡献。

2024-07-07 07:18 UTC, closed without merging

2024-07-07 07:19 UTC, ApartTUSITU commented
另外，请您遵循git message规范。

2024-07-07 07:32 UTC, MCSeekeri commented
> 请您逐步证明自己的实力，本项目随时欢迎您的贡献。

了解，已经重构为原创项目。

2024-07-07 07:34 UTC, liulyxandy-codemao requested changes

2024-07-07 07:34 UTC, liulyxandy-codemao commented on but.service
> +ExecStart=/usr/local/bin/but
用户安装的地址不一定就在这里，需要在某个合适的时机创建软链接。

2024-07-07 07:34 UTC, liulyxandy-codemao commented on src/main.rs
>  无参数启动将开始直接备份。
```suggestion

```

这边有点啰嗦，删去即可

2024-07-07 07:34 UTC, liulyxandy-codemao commented on src/main.rs
> +    println!("but v0.3，文件夹备份工具。\n@Stevesuk0\nrefactor by @liulyxandy-codemao");
```suggestion
    println!("but v0.3，文件夹备份工具。");
```

\n不易读，建议直接删去作者。

2024-07-07 07:34 UTC, liulyxandy-codemao commented on src/main.rs
> +fn write_config_file(path: &str, cfg: &Config) -> Result<(), std::io::Error> {
```suggestion
fn write_config_file(path: &PathBuf, cfg: &Config) -> Result<(), std::io::Error> {
```
不应修改有含义的类型

2024-07-07 07:34 UTC, liulyxandy-codemao commented on src/main.rs
> +        for path in &config_paths {
热重载好，但性能开销过大。况且本项目体量较小，不适宜在细节上如此精细。

2024-07-07 07:34 UTC, liulyxandy-codemao commented on src/main.rs
> +                        println!("{} 没有检测到文件更改，会在文件修改时继续备份", item.name);
同理，全量备份即可，无需校验是否存在更改

2024-07-07 07:34 UTC, liulyxandy-codemao commented on src/main.rs
> +                    compress_folder(item.from.as_str(), dest_path.as_str(), &current_config.settings.compression).expect("压缩失败");
expect会导致panic，程序运行终止，不宜这样处理（原程序亦如此）
可match捕获错误后写入日志

2024-07-07 07:34 UTC, liulyxandy-codemao commented on src/main.rs
> +            let zipfile = std::fs::File::create(dest).unwrap();
```suggestion
            let zipfile = File::create(dest).unwrap();
```
与209行统一

2024-07-07 07:34 UTC, liulyxandy-codemao commented on README.md
> +将 `but.service` 文件复制到 `/etc/systemd/system/` 目录，并执行以下命令：
此次应加上对软链接的设置

2024-07-07 07:34 UTC, ApartTUSITU commented
看了一下您的代码：三个配置文件拼接在一起、旧内容几乎使用生成式AI重写。鉴定您没有为本项目贡献代码的能力，请不要装逼。

2024-07-07 07:36 UTC, MCSeekeri commented
> 看了一下您的代码：三个配置文件拼接在一起、旧内容几乎使用生成式AI重写。鉴定您没有为本项目贡献代码的能力，请不要装逼。

如果您认为提交 PR 是装逼，那么我想我们也没有什么好说的了。

2024-07-07 07:38 UTC, MCSeekeri commented on README.md
> +将 `but.service` 文件复制到 `/etc/systemd/system/` 目录，并执行以下命令：
我个人倾向于直接复制配置文件，而不是软链接，毕竟本身配置文件也不大……

2024-07-07 07:39 UTC, MCSeekeri commented on but.service
> +ExecStart=/usr/local/bin/but
一般来说 /usr/local 是由用户全权负责，如果未来的某个时间点能够针对发行版打包，那么到时候可以改成更合适的路径，此处更像是一个占位符。

2024-07-07 07:41 UTC, ApartTUSITU commented
> > 看了一下您的代码：三个配置文件拼接在一起、旧内容几乎使用生成式AI重写。鉴定您没有为本项目贡献代码的能力，请不要装逼。
> 
> 如果您认为提交 PR 是装逼，那么我想我们也没有什么好说的了。

您的水平无法为该项目贡献。

2024-07-07 07:41 UTC, liulyxandy-codemao commented on README.md
> +将 `but.service` 文件复制到 `/etc/systemd/system/` 目录，并执行以下命令：
> 我个人倾向于直接复制配置文件，而不是软链接，毕竟本身配置文件也不大……

我指的是对but可执行文件的软链接设置。

用户在使用but时可能不会装在/usr/local/bin下，需要在这个地方进行引导，让用户设置软链接将程序链接到/usr/local/bin/but处，以便服务运行。

2024-07-07 07:42 UTC, MCSeekeri commented on src/main.rs
> +                        println!("{} 没有检测到文件更改，会在文件修改时继续备份", item.name);
就我个人的经验来讲，如果每次都是重复性的全量备份，更合适的方式是使用 cron,没有必要单独写一个程序，所以加入了文件修改的校验。
不过目前还是很粗糙的读取最后修改时间，也没测试过文件量过大时对系统的占用，这确实是个问题。

2024-07-07 07:44 UTC, MCSeekeri commented on README.md
> +将 `but.service` 文件复制到 `/etc/systemd/system/` 目录，并执行以下命令：
> > 我个人倾向于直接复制配置文件，而不是软链接，毕竟本身配置文件也不大……
> 
> 我指的是对but可执行文件的软链接设置。
> 
> 用户在使用but时可能不会装在/usr/local/bin下，需要在这个地方进行引导，让用户设置软链接将程序链接到/usr/local/bin/but处，以便服务运行。

了解了，确实这样更加合适。
等到未来的某一时间点也可修改为更符合当前规范的 /usr/bin

2024-07-07 07:45 UTC, liulyxandy-codemao commented on README.md
> +将 `but.service` 文件复制到 `/etc/systemd/system/` 目录，并执行以下命令：
```suggestion
要作为系统服务运行，你需要将 `but` 放在 `/usr/local/bin` 目录下。为了减少工作量，你可以执行`ln -s <but的完整目录>  /usr/local/bin/but`以创建软链接。

将 `but.service` 文件复制到 `/etc/systemd/system/` 目录，并执行以下命令：

```

像这样

2024-07-07 08:00 UTC, liulyxandy-codemao commented on src/main.rs
> +                        println!("{} 没有检测到文件更改，会在文件修改时继续备份", item.name);
> 不过目前还是很粗糙的读取最后修改时间，也没测试过文件量过大时对系统的占用，这确实是个问题。

换做我第一次做这个功能的话，也是读取最后修改时间。况且目前没有合适的替代方法，所以没有关系。

每次都全量备份，只会增加存储的负担，减少程序运行内存的负担；
而递归对程序检查最后修改时间，减轻了存储的负担，但对运行时的性能存在影响。

两者各有得失，可在配置文件中增加相应的设置项，让用户自行抉择。

2024-07-07 08:01 UTC, liulyxandy-codemao commented on src/main.rs
> +fn write_config_file(path: &str, cfg: &Config) -> Result<(), std::io::Error> {
是我脑抽了，抱歉（

2024-07-07 08:02 UTC, liulyxandy-codemao commented on src/main.rs
> +                    compress_folder(item.from.as_str(), dest_path.as_str(), &current_config.settings.compression).expect("压缩失败");
程序中还有大量的unwrap，需要进一步进行优化。

2024-07-07 08:20 UTC, liulyxandy-codemao commented on src/main.rs
>  无参数启动将开始直接备份。
59a2089c fixed.

2024-07-07 08:20 UTC, liulyxandy-codemao commented on src/main.rs
> +    println!("but v0.3，文件夹备份工具。\n@Stevesuk0\nrefactor by @liulyxandy-codemao");
59a2089c fixed.

2024-07-07 08:21 UTC, liulyxandy-codemao commented on src/main.rs
> +                        println!("{} 没有检测到文件更改，会在文件修改时继续备份", item.name);
59a2089c 直接删去，待后续优化

2024-07-07 08:23 UTC, liulyxandy-codemao commented on src/main.rs
> +        for path in &config_paths {
59a2089c 删去

2024-07-07 08:28 UTC, liulyxandy-codemao commented on src/main.rs
> +                        println!("{} 没有检测到文件更改，会在文件修改时继续备份", item.name);
59a2089c 与 07d8c262 完全删去，待后续完善

2024-07-07 08:30 UTC, liulyxandy-codemao commented on README.md
> +将 `but.service` 文件复制到 `/etc/systemd/system/` 目录，并执行以下命令：
e2d8c534 fixed

2024-07-07 08:31 UTC, liulyxandy-codemao commented on src/main.rs
> +            let zipfile = std::fs::File::create(dest).unwrap();
db397664 fixed

2024-07-07 08:37 UTC, liulyxandy-codemao commented on src/main.rs
> +                    compress_folder(item.from.as_str(), dest_path.as_str(), &current_config.settings.compression).expect("压缩失败");
3a14922a 优化

2025-01-24 02:10 UTC, liulyxandy-codemao commented
时隔近半年，今天又仔细看了一眼这个PR的内容。

有些地方合理性的确有待商酌，就像是在一个如此小型轻量的工具中引入热重载，在我看来实在是有些不必要；
但也有些地方并没有实质性上的问题，像是支持`zstd`压缩、去除无用依赖之类。

若单从PR质量上来看，在经过一轮的修改请求之后，其质量已经足以合并入本仓库。

cc一下组织的几位成员 @Stevesuk0 @bzym2 

> 插句题外话，话说`SO-TS/but`什么时候被transfer到`the-OmegaLabs/but`了（？

2025-01-24 02:44 UTC, liulyxandy-codemao commented
我会将这个PR里修改过的内容放到一个新分支中。